# Generated by Django 5.1.4 on 2025-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('not_installed', 'Not Installed')], max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Module',
            },
        ),
    ]
